from pydantic import BaseModel

class EntityAddress(BaseModel):
    street: str
    city: str
    region: str  # State/County
    postal_code: str
    country: str
    po_box: str = None

class CorporateEntity(BaseModel):
    legal_name: str
    registration_number: str
    tax_id: str
    address: EntityAddress
    incorporation_date: str

class VisendiGlobal(BaseModel):
    usa_entity: CorporateEntity
    kenya_entity: CorporateEntity

# --- VERIFIED DATA INJECTION ---
visendi_identity = VisendiGlobal(
    usa_entity=CorporateEntity(
        legal_name="VISENDI56 LLC",
        registration_number="1387664800024",  # File Number from MN Secretary of State
        tax_id="92-3622772",  # EIN from IRS
        incorporation_date="2023-04-19",
        address=EntityAddress(
            street="5200 Wilson Rd, Ste 150",
            city="Edina",
            region="MN",
            postal_code="55424",  # Validated Postal Code for Edina, MN
            country="USA"
        )
    ),
    kenya_entity=CorporateEntity(
        legal_name="VISENDI56 INVESTMENT LIMITED",
        registration_number="PVT-MKUMQYEX",  # Company Number from BRS
        tax_id="P052221589C",  # KRA PIN
        incorporation_date="2023-05-22",
        address=EntityAddress(
            street="The Billows, Ring Rd, Kilimani",  # Updated Physical Location
            city="Nairobi",
            region="Nairobi County",
            postal_code="00200",
            country="Kenya",
            po_box="35827"  # PO Box from CR12
        )
    )
)

def get_legal_footer(entity="KENYA"):
    """
    Returns the legally binding footer for documents generated by iLuminara.
    """
    if entity == "USA":
        ent = visendi_identity.usa_entity
        return f"{ent.legal_name} | EIN: {ent.tax_id} | {ent.address.street}, {ent.address.city}, {ent.address.region} {ent.address.postal_code}, {ent.address.country}"
    else:
        ent = visendi_identity.kenya_entity
        return f"{ent.legal_name} | Reg: {ent.registration_number} | PIN: {ent.tax_id} | PO Box {ent.address.po_box}-{ent.address.postal_code}, {ent.address.street}, {ent.address.city}, {ent.address.country}"