# .readthedocs.yaml
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install -r requirements.txt
    post_install:
      - pip install sphinx sphinx_rtd_theme mkdocs mkdocs-material
sphinx:
  configuration: docs/conf.py
mkdocs:
  configuration: mkdocs.yml
python:
  install:
    - requirements: requirements.txt
