#!/bin/bash
# GitHub Codespace Validation Script
# Optimized for Codespace environment

echo "🚀 Starting GitHub Codespace Enterprise Validation"
echo "=================================================="

# Create directories
mkdir -p ./reports ./logs

# Detect tech stack
echo "🔍 Detecting tech stack..."
TECH_STACK=""

if [ -f "package.json" ]; then
    echo "✅ Detected: Node.js"
        TECH_STACK+="nodejs "
        fi

        if [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
            echo "✅ Detected: Python"
                TECH_STACK+="python "
                fi

                if [ -f "pom.xml" ]; then
                    echo "✅ Detected: Java (Maven)"
                        TECH_STACK+="java "
                        fi

                        if [ -f "go.mod" ]; then
                            echo "✅ Detected: Go"
                                TECH_STACK+="go "
                                fi

                                if [ -f "Dockerfile" ]; then
                                    echo "✅ Detected: Docker"
                                        TECH_STACK+="docker "
                                        fi

                                        if [ -f "*.tf" ] || [ -d ".terraform" ]; then
                                            echo "✅ Detected: Terraform"
                                                TECH_STACK+="terraform "
                                                fi

                                                echo ""
                                                echo "📊 Detected Tech Stack: $TECH_STACK"
                                                echo ""

                                                # Check for uncommitted changes
                                                echo "📁 Git Repository Analysis"
                                                echo "--------------------------"
                                                if [ -d ".git" ]; then
                                                    CHANGES=$(git status --porcelain | wc -l)
                                                        if [ "$CHANGES" -gt 0 ]; then
                                                                echo "⚠️  Uncommitted changes detected: $CHANGES files"
                                                                        git status --short
                                                                            else
                                                                                    echo "✅ No uncommitted changes"
                                                                                        fi
                                                                                            
                                                                                                BRANCH=$(git branch --show-current)
                                                                                                    echo "🌿 Current branch: $BRANCH"
                                                                                                        
                                                                                                            # Check for large files
                                                                                                                echo "📦 Checking for large files..."
                                                                                                                    find . -type f -size +1M -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./vendor/*" | head -10
                                                                                                                    else
                                                                                                                        echo "ℹ️  Not a git repository"
                                                                                                                        fi

                                                                                                                        echo ""

                                                                                                                        # Security checks
                                                                                                                        echo "🔒 Basic Security Checks"
                                                                                                                        echo "-----------------------"

                                                                                                                        # Check for sensitive files
                                                                                                                        echo "🔍 Scanning for sensitive files..."
                                                                                                                        SENSITIVE_FILES=$(find . -type f \( -name "*.key" -o -name "*.pem" -o -name "id_rsa" -o -name ".env*" -o -name "*password*" -o -name "*secret*" \) \
                                                                                                                            -not -path "./node_modules/*" -not -path "./.git/*" 2>/dev/null | wc -l)

                                                                                                                            if [ "$SENSITIVE_FILES" -gt 0 ]; then
                                                                                                                                echo "⚠️  Found $SENSITIVE_FILES potentially sensitive files"
                                                                                                                                    find . -type f \( -name "*.key" -o -name "*.pem" -o -name "id_rsa" -o -name ".env*" \) \
                                                                                                                                            -not -path "./node_modules/*" -not -path "./.git/*" 2>/dev/null | head -5
                                                                                                                                            else
                                                                                                                                                echo "✅ No sensitive files detected"
                                                                                                                                                fi

                                                                                                                                                # Shell script linting
                                                                                                                                                if command -v shellcheck &> /dev/null; then
                                                                                                                                                    echo "📝 Checking shell scripts..."
                                                                                                                                                        find . -name "*.sh" -not -path "./node_modules/*" -not -path "./.git/*" -exec shellcheck {} \;
                                                                                                                                                        else
                                                                                                                                                            echo "ℹ️  Install shellcheck for shell script linting"
                                                                                                                                                            fi

                                                                                                                                                            echo ""

                                                                                                                                                            # Tech-specific validations
                                                                                                                                                            echo "⚙️  Technology-Specific Validation"
                                                                                                                                                            echo "---------------------------------"

                                                                                                                                                            # Node.js validation
                                                                                                                                                            if [[ $TECH_STACK == *"nodejs"* ]]; then
                                                                                                                                                                echo "📦 Node.js Validation:"
                                                                                                                                                                    if command -v npm &> /dev/null; then
                                                                                                                                                                            echo "  Installing dependencies..."
                                                                                                                                                                                    npm install --silent
                                                                                                                                                                                            
                                                                                                                                                                                                    echo "  Checking for vulnerabilities..."
                                                                                                                                                                                                            npm audit --audit-level=high 2>/dev/null || echo "    No high severity vulnerabilities found"
                                                                                                                                                                                                                    
                                                                                                                                                                                                                            echo "  Running tests..."
                                                                                                                                                                                                                                    npm test 2>/dev/null && echo "    ✅ Tests passed" || echo "    ⚠️  Tests failed or not configured"
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    echo "  Checking for outdated packages..."
                                                                                                                                                                                                                                                            npm outdated 2>/dev/null || echo "    All dependencies up to date"
                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                        echo "  ⚠️  npm not available"
                                                                                                                                                                                                                                                                            fi
                                                                                                                                                                                                                                                                            fi

                                                                                                                                                                                                                                                                            # Python validation
                                                                                                                                                                                                                                                                            if [[ $TECH_STACK == *"python"* ]]; then
                                                                                                                                                                                                                                                                                echo "🐍 Python Validation:"
                                                                                                                                                                                                                                                                                    if command -v python3 &> /dev/null; then
                                                                                                                                                                                                                                                                                            echo "  Checking Python version..."
                                                                                                                                                                                                                                                                                                    python3 --version
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    echo "  Creating virtual environment..."
                                                                                                                                                                                                                                                                                                                            python3 -m venv .venv 2>/dev/null && source .venv/bin/activate
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                            echo "  Installing dependencies..."
                                                                                                                                                                                                                                                                                                                                                    if [ -f "requirements.txt" ]; then
                                                                                                                                                                                                                                                                                                                                                                pip install -r requirements.txt --quiet
                                                                                                                                                                                                                                                                                                                                                                        fi
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                        echo "  Running basic checks..."
                                                                                                                                                                                                                                                                                                                                                                                                python3 -m py_compile $(find . -name "*.py" | head -5) 2>/dev/null && echo "    ✅ Syntax check passed"
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                if command -v pytest &> /dev/null; then
                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  Running tests..."
                                                                                                                                                                                                                                                                                                                                                                                                                                        pytest --tb=short -q 2>/dev/null && echo "    ✅ Tests passed" || echo "    ⚠️  Tests failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                    fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                    fi

                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Docker validation
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if [[ $TECH_STACK == *"docker"* ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "🐳 Docker Validation:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if command -v docker &> /dev/null; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  Building Docker image..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            docker build . --tag codespace-validation 2>/dev/null && echo "    ✅ Build successful" || echo "    ⚠️  Build failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "  Cleaning up..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    docker rmi codespace-validation 2>/dev/null || true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "  ⚠️  Docker not available"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fi

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Performance checks
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "⚡ Performance Checks"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "-------------------"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "📊 File count analysis:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  Total files: $(find . -type f -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./vendor/*" | wc -l)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "  Total directories: $(find . -type d -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./vendor/*" | wc -l)"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "📈 Largest files:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    find . -type f -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./vendor/*" -exec du -h {} + 2>/dev/null | sort -rh | head -5

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo ""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Generate summary report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "📋 Validation Summary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "===================="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "Generated: $(date)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "Tech Stack: $TECH_STACK"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "Repository Status: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'Not a git repo')"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "Sensitive Files: $SENSITIVE_FILES"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Save report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cat > ./reports/validation_summary_$(date +%Y%m%d_%H%M%S).md << EOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Validation Report
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ## Generated: $(date)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ### Tech Stack Detected
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $TECH_STACK

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ### Git Status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Branch: $(git branch --show-current 2>/dev/null || echo 'N/A')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Uncommitted Changes: $CHANGES

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ### Security Findings
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - Sensitive Files: $SENSITIVE_FILES

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ### Recommendations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1. Review any sensitive files found
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2. Run comprehensive test suite
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    3. Update dependencies regularly

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    *Generated by GitHub Codespace Validation Script*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    EOF

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "✅ Validation completed!"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "📄 Report saved to: ./reports/validation_summary_*.md"
