# Cloud Run service configuration for iLuminara Web Frontend
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: iluminara-web
  labels:
    app: iluminara
    tier: frontend
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/client-name: 'cloud-console'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/iluminara-web:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: '1000m'
              memory: 512Mi
          env:
            - name: PORT
              value: '8080'
            - name: FIREBASE_PROJECT_ID
              value: 'iluminara-core'
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
